# SPDX-License-Identifier: GPL-3.0-or-later
---
# tasks file for roles/pve-initial

- name: Include no-nag tasks
  ansible.builtin.include_tasks: no-nag.yml

- name: Include IPMI exporter tasks
  ansible.builtin.include_tasks: ipmi.yml
